### ISSUE TITLE
A little idea on what this list might include

### ISSUE THREAD

**Issue by imcaffrey** [hkirat/awesome-competitive-coding#5]
Hi friend, this list currently contains some topics and related problems and this is fantastic. Thanks a lot for your work!

In my opinion, a list on competitive-programming might be better to include some other training resources like discussions on quora, famous papers, template library, etc. In other words, this list should not only include what to learn about during training, but also how to train in this field.

I thought about creating a Pull Request but it seems that this change might be a little too big for the current structure in this list. For example, we might put the Algorithms in a section and Data_Structure in another.

I noticed that this list was intended for `Topic wise Theory and Questions to Get You Started`, but I believe what we do should be good enough for people from newbie to IGM.

Looking forward to ideas, and thanks.

**Comment by hkirat** [comment]
+1
I had the idea of adding discussions on quora and platforms like codeforces for people to get motivated in this field. I think the structure should be changed to include two broad topics of "Topics" and "Discussion". This would help keep the repo differentiated in terms of if the person wants to learn a specific topic or read on more general stuff.

**Comment by imcaffrey** [comment]
:+1:

**Comment by imcaffrey** [comment]
Besides, I think the way you classify the subjects seems need improving.D
Personal opinion... You know, there are obviously so many more subjects and you just can't add them all in the miscellaneous part.

**Comment by hkirat** [comment]
The reason they were added under miscellaneous was that there was not a lot of content available on them..And there was no point of adding a new heading just for one or 2 links.
As soon as I find more content on any of them I'll move them to their personal heading

**Comment by hkirat** [comment]
So do you want to work on the restructuring @imcaffrey ?

**Comment by imcaffrey** [comment]
So how do you plan to restructure this list @hkirat ?

**Comment by hkirat** [comment]
As I mentioned above creating two sub headings, "Topics" and "Discussions"
But first we need to make sure we have enough discussions on CC

**Comment by imcaffrey** [comment]
@hkirat In my opinion, I shall just maintain another list (started months ago), which might provide a broader view for competitive-programming. Honestly, this list is fantastic with many ideas for getting started, and I doubt if I am the right person to restructure this after you've done so much for this list. I have to say thanks a lot as this list actually helped me a lot.

In fact, it might be a better idea if we maintain two lists, one for novice in a detailed way like this, and another for a broader vision.D

**Comment by hkirat** [comment]
ok sure..go ahead!
